### ISSUE TITLE
Android - Blue + White screen after downloading files

### ISSUE THREAD

**Issue by GaWr26** [RocketChat/Rocket.Chat.Cordova#25] opened 2015-11-24 09:25 UTC
I installed the app on two devices, Nexus 5 Android 6.0 & Helix Tablet Android 4.4.
Both show only a white screen after logging in to server and downloading files.

**Comment by GaWr26** [comment] 2015-11-24 09:45
I just tired again and after logging in to the demo server first, login to our server also works.

**Comment by rodrigok** [comment] 2015-11-25 11:16
@flashguy22 can you test with the new version (Beta 5 https://github.com/RocketChat/Rocket.Chat.Cordova/releases/tag/2.0.0.beta.5)?

This version was released right now and will be available in the App Stores in a few minutes.

**Comment by Sing-Li** [comment] 2016-01-19 04:44
![screenshot_2016-01-18-11-51-47](https://cloud.githubusercontent.com/assets/122633/12409902/1a2f8a08-be3d-11e5-9e0b-c6814e86780f.png)

Confirmed this will happen randomly with mobile client.  Seems to be some race condition on the first load of the login screen.

When it works - the white bar expands into the full login.  But when it doesn't work, you just get the white bar.  And restarting the app does not get it to 'retry' again - it only shows the bar above.

Especially obvious when using a slow-link connect to a Raspberry Pi (slower) server.

This _also_ happens randomly on iOS client.

**Comment by rodrigok** [comment] 2016-01-19 13:51
Some times this is related with server heavy load. Now we have the "connection" bar in the login screen to, so you can see if the app is trying to connect the websocket.

**Comment by Sing-Li** [comment] 2016-01-19 15:23
It happens AFTER you add a new server, validating-downloading 1/9, 2/9, 3/9 ... etc.  And before the login screen is shown for the very first time.
When this happens on the Cordova app, it stops retrying on displaying login screen altogether. No connection bar.
And then it also seems to cache the version of the page that stopped trying. So the next time you restart the app, you only get the screen above.
End result is that user cannot login ever again.  Until he/she drop the server, and try again - and again.

Further investigation with @rodrigok  leads to issue #59

**Comment by kiiada** [comment] 2016-01-21 02:12
This problem was resolved when I toggled the "show form-based login" on and off under admin settings. I also made some other changes to the server around this time, can anyone reproduce this?

**Comment by Johann-Snapp** [comment] 2016-02-08 10:37
@bukkits- it doesn't work for me.

**Comment by rodrigok** [comment] 2016-04-04 13:49
Should be fixed in the latest Rocket.Chat server version, please reopen this issue if not.

**Closed as completed by rodrigok** 2016-04-04 13:49 UTC
Labels: bug, waiting response

**Comment by nbaum** [comment] 2016-06-23 17:19
It's happening for me right now on the current beta download.

**Comment by geekgonecrazy** [comment] 2016-06-24 16:21
@nbaum do you still have this?  Which beta download are you referring to?

**Comment by nbaum** [comment] 2016-06-24 16:41
It was the beta download of the server, from https://rocket.chat/releases/develop/download, along with whatever version of the Android app would have been in the Google Play store yesterday!

I've switched back to the stable build of the server and am not seeing this problem in that version. Perhaps there is a version incompatibility between server and client?

**Comment by Gigelfisch** [comment] 2017-12-15 15:29
Unfortunately, I ran into this Problem. I installed the Rocket.Chat App from the Google Play Store and proceeded as recommended (connect to https://open.rocket.chat ). The download of the files is shown and finally a white screen appears. Going "Back" in the app shows the connection screen for a very short time until the white screen appears again. I cannot connect to the desired server nor change the server list. I don't know if it helps, my phone runs on Android 7.1.1

**Comment by Viktova** [comment] 2017-12-19 13:37
issue persists on android (lenovo, p8 lite, oneplus2, samsung s7)

**Comment by reza899** [comment] 2017-12-28 08:18
this issue after upgrading to 0.60 appears again. 
no device can be using rocket by this app. white screen show and no menu.

**Comment by rpahle** [comment] 2017-12-28 10:44
same problem with 0.60 and current android app
white screen appears after setting the server and downloading files. No menu, no login - just a white screen
this happens for all the 0.60-rc versions as well, downgrading to 0.59 is not possible, because of the database migration

**Comment by rodrigok** [comment] 2017-12-28 12:49
Guys, we are planing to remove the cordova app from app stores soon, do you have problems using the native ones (Rocket.Chat+)?

**Comment by reza899** [comment] 2017-12-30 06:05
@rodrigok cordova app has better ui.
because of poor menu of native app (rocket.chat+), it's not support UTF-8 character (like Persian)
also, status lights are cache and not shown correctly.
so, for me cordova is better.

**Comment by fadanner** [comment] 2017-12-30 10:07
@rodrigok Furthermore the android version is not using display names instead of usernames (in LDAP environments, In configured).
That's a knockout for Android native version for us.

**Comment by rpahle** [comment] 2017-12-31 04:05
@rodrigok I agree with the better UI and status lights of the cordova app, that was for us the initial draw to use it (so this would be our preferred app. Rocket.Chat+ allows us to log in, but then it tries to load endlessly (e.g. three dots rotating). So, at the moment (0.60.2) neither one works for us.

**Comment by rodrigok** [comment] 2018-01-02 12:44
@rafaelks can you check that issues?

**Comment by rafaelks** [comment] 2018-01-02 12:50
@reza899 Are you using the latest version of Google Play? What's a "poor menu"? You mean the lack of options?

@fadanner We aren't support this issues yet, but we'll in 2.0.0 (will write more about it below).

@rpahle Are you using our host solution? And are you using the app from Google Play?

Guys, we're working really hard to rewrite our native Android app and it's getting really awesome. All your feedback and reports are very important. You can follow the development of this version here: https://github.com/RocketChat/Rocket.Chat.Android/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.0.0 and here: https://github.com/RocketChat/Rocket.Chat.Android/tree/develop-2.x.

Thank you!

**Comment by rpahle** [comment] 2018-01-05 16:55
@rafaelks We are using the app from google play (both Rocket.Chat and Rocket.Chat+) and can get neither to work since we upgraded to the 60 release. We are using a self hosted solution - at the moment version 0.60.3. Everything worked fine in 0.59.3.

**Comment by rafaelks** [comment] 2018-01-08 15:51
@rpahle Can you confirm that you're using the version 1.1.0 of Rocket.Chat+? If you're using our cloud solution, please tell me what's your domain so @geekgonecrazy can take a look if there's anything we can do about it.

**Comment by rpahle** [comment] 2018-01-09 19:54
@rafaelks @geekgonecrazy Yes, its Rocket.Chat+ 1.1.0. Domain is https://chat.chain-builder.net The behavior has changed, it does not endlessly search, but it now shows broken pipe: see image.
![screenshot_20180109-144632](https://user-images.githubusercontent.com/5544619/34740269-ccde7608-f54c-11e7-9437-e23b8ebc2e2a.jpg)

**Comment by rafaelks** [comment] 2018-01-10 15:54
@rpahle @geekgonecrazy I was trying to see if your server can do the Switching Protocols, but it doesn't work. Your server needs to be able to finish this request:

```shell
$ curl -i -N -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Host: chat.chain-builder.net" -H "Origin: chat.chain-builder.net" -H "Sec-WebSocket-Key: fVXESE8fjBMx8HheW0YlZQ==" -H "Sec-WebSocket-Version: 13" https://chat.chain-builder.net/websocket
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: dyU1fPKS9c9nPGo2mPsrQv40G9E=
X-Powered-By: Ratchet/0.3.6
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000; includeSubDomains
```

Can you take a look on this? Maybe @geekgonecrazy can help you. Make sure you're using a version of Nginx/Apache that supports WebSocket please.

**Comment by rpahle** [comment] 2018-01-10 21:29
@rafaelks @geekgonecrazy 
Thanks guys, this helped a lot. It seems another application had caught the websocket request. We now made sure that the websocket requests get forwarded correctly and both android applications started working.

**Comment by geekgonecrazy** [comment] 2018-01-11 06:39
Perfect :)
