### ISSUE TITLE
Sidebar goes over button bar

### ISSUE THREAD

**Issue by miscs** [RocketChat/Rocket.Chat.Cordova#15] opened 2015-11-19 12:49 UTC
Samsung Galaxy S6 Edge, Android 5.1.1

Just a blank grey column....

**Comment by graywolf336** [comment] 2015-11-19 15:37
Was you connected to the demo server or your own?

**Comment by miscs** [comment] 2015-11-19 16:14
I was connected with my own server but pulled fresh docker image just this morning...

**Comment by Sing-Li** [comment] 2015-11-19 16:17
Which 'docker image' ?

**Comment by miscs** [comment] 2015-11-19 16:22
Digest: sha256:20a1f91ce1a1affe0614c013613d1679a96a21cbb85c0f457707672d6ae663ed
Status: Image is up to date for rocketchat/rocket.chat:latest

**Comment by graywolf336** [comment] 2015-11-19 16:25
I don't know much about the Docker images, but I wonder if they're running with the meteor arguments `--mobile-server http://<serverip:port>` as that's required for the phone to connect and communicate successfully.

**Comment by miscs** [comment] 2015-11-19 16:29
the app works quite ok (sending / receiving messages). so i think it´s enabled....
I can also see the side menu as long as the channel loads. but when it´s loaded the icons disappear.

**Comment by graywolf336** [comment] 2015-11-19 22:33
I can confirm. It appears there when the channel is loading, but that's it. They do reappear though when your phone's screen resizes, such as going from portrait to landscape.

**Comment by miscs** [comment] 2015-11-20 08:32
with the new beta I first thought this is fixed because the menu showed up at first channel view. but after swichting between some channels the menu is gone again.
as @graywolf336 mentioned phone resize brings the menu back

**Comment by pschonder** [comment] 2015-11-22 11:34
I'm facing the same or maybe related problem. redrawing the sidebar-element fixes the problem sometimes. The Problem was there also with the "old" app. I think it's not an cordova-issue and is affecting all mobile-web-views of the app.
![rocket chat-right-sidebar-bug](https://cloud.githubusercontent.com/assets/66947/11323565/3042041a-9115-11e5-81aa-7ee9f80b0568.gif)

**Comment by marceloschmidt** [comment] 2015-11-25 19:21
Fixed in https://github.com/RocketChat/Rocket.Chat/commit/df525d6d5bf90578b754be6f891234dbe7a452a2

**Comment by marceloschmidt** [comment] 2015-12-02 18:19
We had to revert this issue and solve it via CSS. Please @rcaferati take a look.

**Comment by pschonder** [comment] 2015-12-18 12:55
@rcaferati can I provide some more information to identify this issue?

**Comment by mrplow** [comment] 2016-02-12 05:37
This happens using the official Android app connecting to the demo server and our own server
Using the mobile browser works fine though.
![gif_20160211_211200](https://cloud.githubusercontent.com/assets/1490165/12999759/8e4b0a34-d107-11e5-9284-93956bc7aca4.gif)

**Comment by mrplow** [comment] 2016-02-20 23:07
6065cf6 fixed this for me!

**Closed as completed** 2016-02-26 12:41 UTC
Labels: bug
