### ISSUE TITLE
Cannot scroll up in ios Cordova app

### ISSUE THREAD

**Issue by Syirrus** [RocketChat/Rocket.Chat.Cordova#167] opened 2016-12-28 18:50 UTC
I've installed the latest and greatest. 
Basically, the Rocket.Chat loads okay, but when I try to scroll though the chats I notice that I can scroll down, but when I try to scroll up it doesn't work. In order to scroll down I have to scroll up and then immediately scroll down. I've tried with and without Xwalk / cross walk installed. Any ideas?  I'm using iOS engine 4.3.1

**Comment by Pross** [comment] 2016-12-29 17:27
Ive found if im scrolling buy dragging the very far left of the screen it mostly works. Still not brilliant though

**Comment by engelgabriel** [comment] 2017-01-04 18:11
Hi, this is a duplicate of https://github.com/RocketChat/Rocket.Chat/issues/5401 and we are working on it :) Thanks for reporting.

**Closed as completed by engelgabriel** 2017-01-04 18:11 UTC
